"""add_stripe_billing_fields_to_institution

Revision ID: 66a9be316807
Revises: a34b73151e8a
Create Date: 2026-09-24 01:03:58.190560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a9be316807'
down_revision = 'a34b73151e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('subscription_status', sa.String(length=20), nullable=False, server_default='ACTIVE'))
        batch_op.create_index(batch_op.f('ix_institutions_stripe_customer_id'), ['stripe_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_institutions_stripe_subscription_id'), ['stripe_subscription_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institutions_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_institutions_stripe_customer_id'))
        batch_op.drop_column('subscription_status')
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
