"""baseline

Revision ID: 7e6a7439c05b
Revises: 
Create Date: 2026-09-24 00:53:01.028445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e6a7439c05b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=30), nullable=False),
    sa.Column('bus_code', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.Integer(), nullable=True),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lng', sa.Float(), nullable=True),
    sa.Column('last_location_update', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_buses_bus_code'), ['bus_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_buses_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_buses_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_buses_registration_number'), ['registration_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_buses_route_id'), ['route_id'], unique=False)

    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('profile_photo', sa.String(length=255), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=False),
    sa.Column('license_expiry', sa.String(length=20), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('assigned_bus_id', sa.Integer(), nullable=True),
    sa.Column('assigned_route_id', sa.Integer(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lng', sa.Float(), nullable=True),
    sa.Column('last_online_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['assigned_route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drivers_assigned_bus_id'), ['assigned_bus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_assigned_route_id'), ['assigned_route_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_user_id'), ['user_id'], unique=False)

    op.create_table('institutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('plan_tier', sa.String(length=20), nullable=False),
    sa.Column('invite_code', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_institutions_invite_code'), ['invite_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_institutions_slug'), ['slug'], unique=True)

    op.create_table('driver_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('doc_name', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expiry_date', sa.String(length=20), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_documents_driver_id'), ['driver_id'], unique=False)

    op.create_table('driver_trainings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('training_name', sa.String(length=100), nullable=False),
    sa.Column('training_date', sa.String(length=20), nullable=False),
    sa.Column('certificate_file', sa.String(length=255), nullable=True),
    sa.Column('expiry_date', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver_trainings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_trainings_driver_id'), ['driver_id'], unique=False)

    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('estimated_duration_mins', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_routes_institution_id'), ['institution_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('action_link', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('emergency_contact', sa.String(length=20), nullable=True),
    sa.Column('relationship', sa.String(length=50), nullable=True),
    sa.Column('proximity_radius_meters', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_parents_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parents_user_id'), ['user_id'], unique=False)

    op.create_table('stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('stop_name', sa.String(length=100), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('scheduled_pickup_time', sa.String(length=10), nullable=True),
    sa.Column('scheduled_drop_time', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stops_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stops_route_id'), ['route_id'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('roll_number', sa.String(length=30), nullable=False),
    sa.Column('grade_section', sa.String(length=30), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('date_of_birth', sa.String(length=20), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('invite_code', sa.String(length=30), nullable=True),
    sa.Column('invite_used', sa.Boolean(), nullable=False),
    sa.Column('assigned_bus_id', sa.Integer(), nullable=True),
    sa.Column('assigned_route_id', sa.Integer(), nullable=True),
    sa.Column('pickup_stop_id', sa.Integer(), nullable=True),
    sa.Column('drop_stop_id', sa.Integer(), nullable=True),
    sa.Column('photo_filename', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['assigned_route_id'], ['routes.id'], ),
    sa.ForeignKeyConstraint(['drop_stop_id'], ['stops.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['pickup_stop_id'], ['stops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_assigned_bus_id'), ['assigned_bus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_assigned_route_id'), ['assigned_route_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_invite_code'), ['invite_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_students_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_roll_number'), ['roll_number'], unique=True)

    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('trip_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('current_lat', sa.Float(), nullable=True),
    sa.Column('current_lng', sa.Float(), nullable=True),
    sa.Column('current_stop_id', sa.Integer(), nullable=True),
    sa.Column('delay_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['current_stop_id'], ['stops.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trips_bus_id'), ['bus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_route_id'), ['route_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_status'), ['status'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=40), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_bus_id'), ['bus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_is_resolved'), ['is_resolved'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_trip_id'), ['trip_id'], unique=False)

    op.create_table('attendances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('verification_time', sa.DateTime(), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('scan_type', sa.String(length=20), nullable=False),
    sa.Column('is_dropped_off', sa.Boolean(), nullable=False),
    sa.Column('drop_verification_time', sa.DateTime(), nullable=True),
    sa.Column('verified_by_driver_id', sa.Integer(), nullable=True),
    sa.Column('photo_snapshot', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['verified_by_driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'trip_id', name='uq_student_trip_attendance')
    )
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendances_bus_id'), ['bus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_trip_id'), ['trip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_verification_status'), ['verification_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendances_verification_time'), ['verification_time'], unique=False)

    op.create_table('authorized_escorts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('relationship', sa.String(length=50), nullable=False),
    sa.Column('id_proof_number', sa.String(length=50), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('authorized_escorts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_authorized_escorts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_authorized_escorts_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_authorized_escorts_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_authorized_escorts_student_id'), ['student_id'], unique=False)

    op.create_table('driver_safety_telemetries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('fatigue_score', sa.Float(), nullable=True),
    sa.Column('fatigue_level', sa.String(length=30), nullable=True),
    sa.Column('eye_closure_sec', sa.Float(), nullable=True),
    sa.Column('yawn_count', sa.Integer(), nullable=True),
    sa.Column('distraction_event', sa.String(length=40), nullable=True),
    sa.Column('speed_kph', sa.Float(), nullable=True),
    sa.Column('overspeed_warning', sa.Boolean(), nullable=True),
    sa.Column('harsh_braking_warning', sa.Boolean(), nullable=True),
    sa.Column('safety_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('driver_safety_telemetries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_driver_safety_telemetries_bus_id'), ['bus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_safety_telemetries_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_safety_telemetries_fatigue_level'), ['fatigue_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_safety_telemetries_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_driver_safety_telemetries_trip_id'), ['trip_id'], unique=False)

    op.create_table('emergency_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('triggered_by_user_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emergency_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emergency_events_bus_id'), ['bus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_events_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_emergency_events_trip_id'), ['trip_id'], unique=False)

    op.create_table('face_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('feature_vector_json', sa.Text(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.Column('parental_consent_given', sa.Boolean(), nullable=False),
    sa.Column('consent_given_at', sa.DateTime(), nullable=True),
    sa.Column('consent_given_by_user_id', sa.Integer(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consent_given_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('face_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_face_profiles_is_archived'), ['is_archived'], unique=False)
        batch_op.create_index(batch_op.f('ix_face_profiles_parental_consent_given'), ['parental_consent_given'], unique=False)
        batch_op.create_index(batch_op.f('ix_face_profiles_student_id'), ['student_id'], unique=True)

    op.create_table('gps_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gps_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gps_locations_bus_id'), ['bus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gps_locations_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_gps_locations_trip_id'), ['trip_id'], unique=False)

    op.create_table('safe_drop_confirmations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('bus_arrival_time', sa.DateTime(), nullable=True),
    sa.Column('confirmation_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'trip_id', 'stop_id', name='uq_safe_drop_confirmation')
    )
    with op.batch_alter_table('safe_drop_confirmations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safe_drop_confirmations_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_safe_drop_confirmations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_safe_drop_confirmations_stop_id'), ['stop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_safe_drop_confirmations_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_safe_drop_confirmations_trip_id'), ['trip_id'], unique=False)

    op.create_table('stop_proximity_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('distance_meters', sa.Float(), nullable=False),
    sa.Column('estimated_eta_mins', sa.Integer(), nullable=True),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'student_id', 'stop_id', name='uq_trip_student_stop_proximity')
    )
    with op.batch_alter_table('stop_proximity_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stop_proximity_logs_bus_id'), ['bus_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stop_proximity_logs_notified_at'), ['notified_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stop_proximity_logs_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stop_proximity_logs_stop_id'), ['stop_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stop_proximity_logs_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stop_proximity_logs_trip_id'), ['trip_id'], unique=False)

    op.create_table('student_absence_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('absence_date', sa.String(length=20), nullable=False),
    sa.Column('session_type', sa.String(length=30), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('student_absence_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_absence_requests_absence_date'), ['absence_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_absence_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_absence_requests_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_absence_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_absence_requests_student_id'), ['student_id'], unique=False)

    op.create_table('temporary_bus_reassignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('original_bus_id', sa.Integer(), nullable=False),
    sa.Column('temporary_bus_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.String(length=20), nullable=False),
    sa.Column('end_date', sa.String(length=20), nullable=False),
    sa.Column('approved_by_user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['original_bus_id'], ['buses.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['temporary_bus_id'], ['buses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('temporary_bus_reassignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_temporary_bus_reassignments_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_temporary_bus_reassignments_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('temporary_bus_reassignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_temporary_bus_reassignments_student_id'))
        batch_op.drop_index(batch_op.f('ix_temporary_bus_reassignments_is_active'))

    op.drop_table('temporary_bus_reassignments')
    with op.batch_alter_table('student_absence_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_absence_requests_student_id'))
        batch_op.drop_index(batch_op.f('ix_student_absence_requests_status'))
        batch_op.drop_index(batch_op.f('ix_student_absence_requests_parent_id'))
        batch_op.drop_index(batch_op.f('ix_student_absence_requests_created_at'))
        batch_op.drop_index(batch_op.f('ix_student_absence_requests_absence_date'))

    op.drop_table('student_absence_requests')
    with op.batch_alter_table('stop_proximity_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stop_proximity_logs_trip_id'))
        batch_op.drop_index(batch_op.f('ix_stop_proximity_logs_student_id'))
        batch_op.drop_index(batch_op.f('ix_stop_proximity_logs_stop_id'))
        batch_op.drop_index(batch_op.f('ix_stop_proximity_logs_parent_id'))
        batch_op.drop_index(batch_op.f('ix_stop_proximity_logs_notified_at'))
        batch_op.drop_index(batch_op.f('ix_stop_proximity_logs_bus_id'))

    op.drop_table('stop_proximity_logs')
    with op.batch_alter_table('safe_drop_confirmations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safe_drop_confirmations_trip_id'))
        batch_op.drop_index(batch_op.f('ix_safe_drop_confirmations_student_id'))
        batch_op.drop_index(batch_op.f('ix_safe_drop_confirmations_stop_id'))
        batch_op.drop_index(batch_op.f('ix_safe_drop_confirmations_status'))
        batch_op.drop_index(batch_op.f('ix_safe_drop_confirmations_parent_id'))

    op.drop_table('safe_drop_confirmations')
    with op.batch_alter_table('gps_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gps_locations_trip_id'))
        batch_op.drop_index(batch_op.f('ix_gps_locations_timestamp'))
        batch_op.drop_index(batch_op.f('ix_gps_locations_bus_id'))

    op.drop_table('gps_locations')
    with op.batch_alter_table('face_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_face_profiles_student_id'))
        batch_op.drop_index(batch_op.f('ix_face_profiles_parental_consent_given'))
        batch_op.drop_index(batch_op.f('ix_face_profiles_is_archived'))

    op.drop_table('face_profiles')
    with op.batch_alter_table('emergency_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emergency_events_trip_id'))
        batch_op.drop_index(batch_op.f('ix_emergency_events_status'))
        batch_op.drop_index(batch_op.f('ix_emergency_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_emergency_events_bus_id'))

    op.drop_table('emergency_events')
    with op.batch_alter_table('driver_safety_telemetries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_safety_telemetries_trip_id'))
        batch_op.drop_index(batch_op.f('ix_driver_safety_telemetries_timestamp'))
        batch_op.drop_index(batch_op.f('ix_driver_safety_telemetries_fatigue_level'))
        batch_op.drop_index(batch_op.f('ix_driver_safety_telemetries_driver_id'))
        batch_op.drop_index(batch_op.f('ix_driver_safety_telemetries_bus_id'))

    op.drop_table('driver_safety_telemetries')
    with op.batch_alter_table('authorized_escorts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_authorized_escorts_student_id'))
        batch_op.drop_index(batch_op.f('ix_authorized_escorts_parent_id'))
        batch_op.drop_index(batch_op.f('ix_authorized_escorts_is_active'))
        batch_op.drop_index(batch_op.f('ix_authorized_escorts_created_at'))

    op.drop_table('authorized_escorts')
    with op.batch_alter_table('attendances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendances_verification_time'))
        batch_op.drop_index(batch_op.f('ix_attendances_verification_status'))
        batch_op.drop_index(batch_op.f('ix_attendances_trip_id'))
        batch_op.drop_index(batch_op.f('ix_attendances_student_id'))
        batch_op.drop_index(batch_op.f('ix_attendances_bus_id'))

    op.drop_table('attendances')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_trip_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_student_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_is_resolved'))
        batch_op.drop_index(batch_op.f('ix_alerts_institution_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_alerts_bus_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_alert_type'))

    op.drop_table('alerts')
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trips_status'))
        batch_op.drop_index(batch_op.f('ix_trips_route_id'))
        batch_op.drop_index(batch_op.f('ix_trips_institution_id'))
        batch_op.drop_index(batch_op.f('ix_trips_driver_id'))
        batch_op.drop_index(batch_op.f('ix_trips_bus_id'))

    op.drop_table('trips')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_roll_number'))
        batch_op.drop_index(batch_op.f('ix_students_parent_id'))
        batch_op.drop_index(batch_op.f('ix_students_invite_code'))
        batch_op.drop_index(batch_op.f('ix_students_institution_id'))
        batch_op.drop_index(batch_op.f('ix_students_assigned_route_id'))
        batch_op.drop_index(batch_op.f('ix_students_assigned_bus_id'))

    op.drop_table('students')
    with op.batch_alter_table('stops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stops_route_id'))
        batch_op.drop_index(batch_op.f('ix_stops_institution_id'))

    op.drop_table('stops')
    with op.batch_alter_table('parents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parents_user_id'))
        batch_op.drop_index(batch_op.f('ix_parents_institution_id'))

    op.drop_table('parents')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_institution_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_institution_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('routes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_routes_institution_id'))

    op.drop_table('routes')
    with op.batch_alter_table('driver_trainings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_trainings_driver_id'))

    op.drop_table('driver_trainings')
    with op.batch_alter_table('driver_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_driver_documents_driver_id'))

    op.drop_table('driver_documents')
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institutions_slug'))
        batch_op.drop_index(batch_op.f('ix_institutions_invite_code'))

    op.drop_table('institutions')
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drivers_user_id'))
        batch_op.drop_index(batch_op.f('ix_drivers_institution_id'))
        batch_op.drop_index(batch_op.f('ix_drivers_assigned_route_id'))
        batch_op.drop_index(batch_op.f('ix_drivers_assigned_bus_id'))

    op.drop_table('drivers')
    with op.batch_alter_table('buses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_buses_route_id'))
        batch_op.drop_index(batch_op.f('ix_buses_registration_number'))
        batch_op.drop_index(batch_op.f('ix_buses_institution_id'))
        batch_op.drop_index(batch_op.f('ix_buses_driver_id'))
        batch_op.drop_index(batch_op.f('ix_buses_bus_code'))

    op.drop_table('buses')
    # ### end Alembic commands ###
