"""allow_nullable_institution_id_for_super_admin

Revision ID: a34b73151e8a
Revises: 7e6a7439c05b
Create Date: 2026-09-24 00:55:33.452595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a34b73151e8a'
down_revision = '7e6a7439c05b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('institution_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('institution_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
