"""Fix string length limits

Revision ID: efdc0b2f90fe
Revises: 66a9be316807
Create Date: 2026-10-01 23:34:30.818911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efdc0b2f90fe'
down_revision = '66a9be316807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_institutions_stripe_customer_id'), ['stripe_customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_institutions_stripe_subscription_id'), ['stripe_subscription_id'], unique=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('grade_section',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('grade_section',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)

    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institutions_stripe_subscription_id'))
        batch_op.drop_index(batch_op.f('ix_institutions_stripe_customer_id'))

    # ### end Alembic commands ###
